class CfgPatches
{
	class seki_FIR_compat_base
	{
		name="FIR RHS COMPAT";
		requiredVersion=1.98;
		requiredAddons[]=
		{
			"FIR_AirWeaponSystem_US",
			"FIR_PilotCrewPack_US",
			"rhsusf_melb"
		};
		author="SekiGamer";
		units[] = {};
		weapons[] = {};
	};
};
class CfgMagazines
{
	class VehicleMagazine;
	class FIR_Hydra_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_FA18EF_Combined_HP","B_BOMB_PYLON","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_F2A_Combined_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_M229_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_FA18EF_Combined_HP","B_BOMB_PYLON","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_M229_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_F16_Combined_HP","FIR_F16_AG_HP","FIR_FA18EF_Combined_HP","B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_M247_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_M247_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};			
	class FIR_Hydra_M257_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};			
	class FIR_Hydra_M261_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};			
	class FIR_Hydra_M261_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};			
	class FIR_Hydra_M282_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};			
	class FIR_Hydra_M282_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};		
	class FIR_Hydra_WDU4_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};	
	};
	class FIR_Hydra_WDU4_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};			
	};			
	class FIR_Hydra_WP_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};
	class FIR_Hydra_WP_P_21rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};
	class FIR_Hydra_Smoke_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};			
	};
	class FIR_Hydra_Smoke_P_21rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};
	}
	class FIR_APKWS_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10C_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAGR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};
	};
	class FIR_APKWS_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};				
	class FIR_APKWS_M247_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10C_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAGR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};
	};
	class FIR_APKWS_M247_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};
	class FIR_APKWS_M282_P_7rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_F16_Combined_HP","FIR_F16_AG_HP","FIR_FA18EF_Combined_HP","B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","DAR","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};
	class FIR_APKWS_M282_P_19rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F16_Combined_HP", "FIR_F16_AG_HP","FIR_FA18EF_Combined_HP", "B_BOMB_PYLON","FIR_A10_BOMB_HP","FIR_AV8B_AG_HP","FIR_SH_AG_HP","FIR_BLUFOR_AG_HP","FIR_BLUFOR_Combined_HP","FIR_FA181E_AG_HP","FIR_F35B_Combined_HP","FIR_FA18_Combined_HP","RHS_HP_FFAR_ARMY","RHS_HP_FFAR_USMC","B_MISSILE_PYLON","B_AGM65_RAIL","I_AGM65_RAIL","RHS_HP_MELB","RHS_HP_LONGBOW_RACK"};		
	};
	class FIR_AIM9L_P_2rnd_M : VehicleMagazine
	{
		hardpoints[] = {"FIR_A10_AA_HP","FIR_A10C_AA_HP","FIR_BLUFOR_AA_HP","FIR_BLUFOR_Combined_HP","FIR_MQ81_WEP_HP","B_MISSILE_PYLON","RHS_HP_ATAS_AH64"};				
	};
	class FIR_AIM9M_P_1rnd_M : VehicleMagazine
	{
		hardpoints[] = { "FIR_F15E_AA_HP","FIR_F15C_AA_HP","FIR_F15A_AA_HP","FIR_F16_AA_HP", "FIR_F16_Combined_HP","FIR_SH_Wingtip_HP","FIR_FA18EF_Wingtip_HP","FIR_F14_SW_HP","FIR_F2A_AA_HP", "FIR_F2A_Combined_HP","FIR_F22_SW_HP","FIR_BLUFOR_AA_HP","FIR_BLUFOR_Combined_HP","FIR_F23_SW_HP","FIR_MQ81_WEP_HP","FIR_F35B_Wingtip_HP","FIR_F35B_AA_INT_HP","FIR_FA18_Wingtip_HP","B_MISSILE_PYLON","B_BIM9X","I_BIM9X",,"RHS_HP_ATAS_AH64"};
			
	};	
}